// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5y_DdYAmThwGiksBPNHBYJ0gurvFeofY',
    appId: '1:1074180958391:web:0db0441ea3dcab472c8532',
    messagingSenderId: '1074180958391',
    projectId: 'ceibo-taxi',
    authDomain: 'ceibo-taxi.firebaseapp.com',
    storageBucket: 'ceibo-taxi.appspot.com',
    measurementId: 'G-Y09FN8TCRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgfy7YvKK7CX1hP3rswa6Omu132FJkFgc',
    appId: '1:1074180958391:android:816d6060f7cfb6ff2c8532',
    messagingSenderId: '1074180958391',
    projectId: 'ceibo-taxi',
    storageBucket: 'ceibo-taxi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBs9BHQwcb00PSyaxDMWF_vPdCaZfWmjM',
    appId: '1:1074180958391:ios:e2efc985b12c64bc2c8532',
    messagingSenderId: '1074180958391',
    projectId: 'ceibo-taxi',
    storageBucket: 'ceibo-taxi.appspot.com',
    iosBundleId: 'com.example.appTaxis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBs9BHQwcb00PSyaxDMWF_vPdCaZfWmjM',
    appId: '1:1074180958391:ios:e2efc985b12c64bc2c8532',
    messagingSenderId: '1074180958391',
    projectId: 'ceibo-taxi',
    storageBucket: 'ceibo-taxi.appspot.com',
    iosBundleId: 'com.example.appTaxis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5y_DdYAmThwGiksBPNHBYJ0gurvFeofY',
    appId: '1:1074180958391:web:acc8ae143445864a2c8532',
    messagingSenderId: '1074180958391',
    projectId: 'ceibo-taxi',
    authDomain: 'ceibo-taxi.firebaseapp.com',
    storageBucket: 'ceibo-taxi.appspot.com',
    measurementId: 'G-NJM1TM4ZQ3',
  );
}
