// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH46DCEhIrqNd5iwChzwhLh7DMhV2hHlA',
    appId: '1:517076721221:web:63a858a8c1c3f0e0630d2c',
    messagingSenderId: '517076721221',
    projectId: 'rtsg-97a02',
    authDomain: 'rtsg-97a02.firebaseapp.com',
    storageBucket: 'rtsg-97a02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4znR4EVLJgeWgO3UFN8HWAlTNVIU0rE',
    appId: '1:517076721221:android:fab47a66e0b7f20d630d2c',
    messagingSenderId: '517076721221',
    projectId: 'rtsg-97a02',
    storageBucket: 'rtsg-97a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPFTYI_TLyk7eiGmcRWGrLIZ1zfsPxFbw',
    appId: '1:517076721221:ios:988486d80b46251f630d2c',
    messagingSenderId: '517076721221',
    projectId: 'rtsg-97a02',
    storageBucket: 'rtsg-97a02.firebasestorage.app',
    iosBundleId: 'com.ceibocode.rtsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPFTYI_TLyk7eiGmcRWGrLIZ1zfsPxFbw',
    appId: '1:517076721221:ios:db6bba9baafe7f05630d2c',
    messagingSenderId: '517076721221',
    projectId: 'rtsg-97a02',
    storageBucket: 'rtsg-97a02.firebasestorage.app',
    iosBundleId: 'com.example.appTaxis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH46DCEhIrqNd5iwChzwhLh7DMhV2hHlA',
    appId: '1:517076721221:web:fe802830ccf550b2630d2c',
    messagingSenderId: '517076721221',
    projectId: 'rtsg-97a02',
    authDomain: 'rtsg-97a02.firebaseapp.com',
    storageBucket: 'rtsg-97a02.firebasestorage.app',
  );

}